#!/usr/bin/env python3
"""Generate docker-compose.yml, .env, and participants.csv for session 3."""

from __future__ import annotations

import argparse
import csv
import json
import secrets
import string
import subprocess
import sys
from pathlib import Path
from urllib.parse import urlsplit, urlunsplit

INFRA_ROOT = Path(__file__).resolve().parent.parent
DOCKER_DIR = INFRA_ROOT / "docker"
GENERATED_DIR = DOCKER_DIR / "generated"
WORKSPACES_DIR = DOCKER_DIR / "workspaces"
CREDENTIALS_DIR = INFRA_ROOT / "credentials"
TERRAFORM_DIR = INFRA_ROOT / "terraform"


def random_password(length: int = 16) -> str:
    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(length))


def sanitize_repo_url(url: str) -> str:
    parsed = urlsplit(url)
    hostname = parsed.hostname or ""
    netloc = hostname
    if parsed.port:
        netloc = f"{hostname}:{parsed.port}"
    return urlunsplit((parsed.scheme, netloc, parsed.path, parsed.query, parsed.fragment))


def terraform_output_json(name: str | None = None) -> dict:
    command = ["terraform", "output", "-json"]
    if name:
        command.append(name)

    result = subprocess.run(
        command,
        cwd=str(TERRAFORM_DIR),
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        print(
            "Error: terraform output failed. Run 'terraform apply' in infra/terraform first.",
            file=sys.stderr,
        )
        print(result.stderr, file=sys.stderr)
        sys.exit(1)

    return json.loads(result.stdout)


def terraform_output_raw(name: str) -> str:
    result = subprocess.run(
        ["terraform", "output", "-raw", name],
        cwd=str(TERRAFORM_DIR),
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        print(f"Error: terraform output -raw {name} failed.", file=sys.stderr)
        print(result.stderr, file=sys.stderr)
        sys.exit(1)

    return result.stdout.strip()


def write_env(path: Path, passwords: dict[str, str], git_pat: str) -> None:
    lines = ["# Auto-generated - do not commit", ""]
    for owner, password in sorted(passwords.items()):
        prefix = owner.upper()
        lines.append(f"{prefix}_PASSWORD={password}")
        lines.append(f"{prefix}_GIT_PAT={git_pat}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_compose(
    path: Path,
    repos: dict,
    passwords: dict[str, str],
    vm_ip: str,
    base_port: int,
) -> None:
    services: list[str] = []
    for index, owner in enumerate(sorted(repos), start=0):
        port = base_port + index
        repo_url = sanitize_repo_url(repos[owner]["remote_url"])
        services.append(
            f"""  {owner}:
    build: .
    ports:
      - "{port}:8080"
    env_file:
      - .env
    environment:
      PASSWORD: "${{{owner.upper()}_PASSWORD}}"
      GIT_REPO_URL: "{repo_url}"
      GIT_PAT: "${{{owner.upper()}_GIT_PAT}}"
      GIT_USER_NAME: "{owner}"
      GIT_USER_EMAIL: "{owner}@example.local"
    volumes:
      - ../workspaces/{owner}:/home/coder/workshop:rw
    restart: unless-stopped"""
        )

    content = (
        "# Auto-generated by scripts/gen-compose.py\n"
        f"# VM: http://{vm_ip}:{base_port}\n"
        "services:\n"
        + "\n".join(services)
        + "\n"
    )
    path.write_text(content, encoding="utf-8")


def write_participants_csv(
    path: Path,
    repos: dict,
    passwords: dict[str, str],
    vm_ip: str,
    base_port: int,
) -> None:
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=["seat", "owner", "url", "password", "repo_url"],
        )
        writer.writeheader()
        for index, owner in enumerate(sorted(repos), start=0):
            repo_url = sanitize_repo_url(repos[owner]["remote_url"])
            writer.writerow(
                {
                    "seat": str(index + 1),
                    "owner": owner,
                    "url": f"http://{vm_ip}:{base_port + index}",
                    "password": passwords[owner],
                    "repo_url": repo_url,
                }
            )


def prepare_workspace_dirs(owners: list[str]) -> None:
    WORKSPACES_DIR.mkdir(parents=True, exist_ok=True)
    for owner in owners:
        (WORKSPACES_DIR / owner).mkdir(parents=True, exist_ok=True)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Docker Compose for session 3")
    parser.add_argument(
        "--base-port",
        type=int,
        default=None,
        help="First port (default: terraform output base_port)",
    )
    args = parser.parse_args()

    outputs = terraform_output_json()
    repos = outputs["participant_repositories"]["value"]
    vm_ip = outputs["vm_public_ip"]["value"]
    base_port = args.base_port or int(outputs["base_port"]["value"])
    git_pat = terraform_output_raw("azuredevops_git_pat")

    passwords = {owner: random_password() for owner in repos}

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    CREDENTIALS_DIR.mkdir(parents=True, exist_ok=True)
    prepare_workspace_dirs(sorted(repos))

    env_path = GENERATED_DIR / ".env"
    compose_path = GENERATED_DIR / "docker-compose.yml"
    csv_path = CREDENTIALS_DIR / "participants.csv"

    write_env(env_path, passwords, git_pat)
    write_compose(compose_path, repos, passwords, vm_ip, base_port)
    write_participants_csv(csv_path, repos, passwords, vm_ip, base_port)

    print(f"Generated: {compose_path}")
    print(f"Generated: {env_path}")
    print(f"Generated: {csv_path}")
    print(f"Workspaces: {WORKSPACES_DIR} ({len(repos)} directories)")


if __name__ == "__main__":
    main()
