#!/usr/bin/env python3
"""Generate docker-compose.yml, .env, and participants.csv for the workshop VM."""

from __future__ import annotations

import argparse
import csv
import json
import secrets
import string
import subprocess
import sys
from pathlib import Path

INFRA_ROOT = Path(__file__).resolve().parent.parent
DOCKER_DIR = INFRA_ROOT / "docker"
GENERATED_DIR = DOCKER_DIR / "generated"
WORKSPACES_DIR = DOCKER_DIR / "workspaces"
CREDENTIALS_DIR = INFRA_ROOT / "credentials"
TERRAFORM_DIR = INFRA_ROOT / "terraform"
WORKSHOP_SRC = INFRA_ROOT / "workshop"


def random_password(length: int = 16) -> str:
    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(length))


def load_terraform_outputs() -> dict:
    result = subprocess.run(
        ["terraform", "output", "-json"],
        cwd=str(TERRAFORM_DIR),
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        print(
            "Error: terraform output failed. Run 'terraform apply' in infra/terraform first.",
            file=sys.stderr,
        )
        print(result.stderr, file=sys.stderr)
        sys.exit(1)

    raw = json.loads(result.stdout)
    return {key: value["value"] for key, value in raw.items()}


def seat_name(index: int) -> str:
    return f"user{index:02d}"


def write_env(
    path: Path,
    outputs: dict,
    passwords: dict[str, str],
    participant_count: int,
) -> None:
    lines = [
        "# Auto-generated — do not commit",
        f"ARM_CLIENT_ID={outputs['arm_client_id']}",
        f"ARM_CLIENT_SECRET={outputs['arm_client_secret']}",
        f"ARM_TENANT_ID={outputs['arm_tenant_id']}",
        f"ARM_SUBSCRIPTION_ID={outputs['arm_subscription_id']}",
        f"TF_VAR_resource_group_name={outputs['workshop_resource_group_name']}",
        "",
    ]
    for i in range(1, participant_count + 1):
        name = seat_name(i)
        lines.append(f"{name.upper()}_PASSWORD={passwords[name]}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_compose(
    path: Path,
    outputs: dict,
    passwords: dict[str, str],
    base_port: int,
    participant_count: int,
) -> None:
    services: list[str] = []
    for i in range(1, participant_count + 1):
        name = seat_name(i)
        port = base_port + i - 1
        services.append(
            f"""  {name}:
    build: .
    ports:
      - "{port}:8080"
    env_file:
      - .env
    environment:
      PASSWORD: "${{{name.upper()}_PASSWORD}}"
      TF_VAR_owner: "{name}"
      TF_VAR_resource_group_name: "{outputs['workshop_resource_group_name']}"
    volumes:
      - ../workspaces/{name}:/home/coder/workshop:rw
    restart: unless-stopped"""
        )

    content = (
        "# Auto-generated by scripts/gen-compose.py\n"
        "services:\n"
        + "\n".join(services)
        + "\n"
    )
    path.write_text(content, encoding="utf-8")


def write_participants_csv(
    path: Path,
    outputs: dict,
    passwords: dict[str, str],
    base_port: int,
    participant_count: int,
) -> None:
    ip = outputs["vm_public_ip"]
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["seat", "url", "password", "owner"])
        writer.writeheader()
        for i in range(1, participant_count + 1):
            name = seat_name(i)
            port = base_port + i - 1
            writer.writerow(
                {
                    "seat": str(i),
                    "url": f"http://{ip}:{port}",
                    "password": passwords[name],
                    "owner": name,
                }
            )


def sync_workshop_to_workspaces(participant_count: int) -> None:
    import shutil

    for i in range(1, participant_count + 1):
        dest = WORKSPACES_DIR / seat_name(i)
        if dest.exists():
            shutil.rmtree(dest)
        shutil.copytree(WORKSHOP_SRC, dest)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Docker Compose for workshop VM")
    parser.add_argument(
        "-n",
        "--count",
        type=int,
        default=None,
        help="Participant count (default: terraform output participant_count)",
    )
    parser.add_argument(
        "--base-port",
        type=int,
        default=None,
        help="First port (default: terraform output base_port)",
    )
    args = parser.parse_args()

    outputs = load_terraform_outputs()
    participant_count = args.count or int(outputs["participant_count"])
    base_port = args.base_port or int(outputs["base_port"])

    passwords = {seat_name(i): random_password() for i in range(1, participant_count + 1)}

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    WORKSPACES_DIR.mkdir(parents=True, exist_ok=True)
    CREDENTIALS_DIR.mkdir(parents=True, exist_ok=True)

    sync_workshop_to_workspaces(participant_count)

    env_path = GENERATED_DIR / ".env"
    compose_path = GENERATED_DIR / "docker-compose.yml"
    csv_path = CREDENTIALS_DIR / "participants.csv"

    write_env(env_path, outputs, passwords, participant_count)
    write_compose(compose_path, outputs, passwords, base_port, participant_count)
    write_participants_csv(csv_path, outputs, passwords, base_port, participant_count)

    print(f"Generated: {compose_path}")
    print(f"Generated: {env_path}")
    print(f"Generated: {csv_path}")
    print(f"Workspaces: {WORKSPACES_DIR} ({participant_count} copies)")


if __name__ == "__main__":
    main()
